# Generated by Django 5.1.6 on 2025-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_dec",
                    models.CharField(
                        default="",
                        max_length=3,
                        unique=True,
                        verbose_name="Код числовой",
                    ),
                ),
                (
                    "code_str",
                    models.CharField(
                        default="",
                        max_length=3,
                        unique=True,
                        verbose_name="Код строковый",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="Имя"),
                ),
                (
                    "repr",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Валюта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "ordering": ["code_str"],
                "indexes": [
                    models.Index(
                        fields=["code_dec"], name="classifiers_code_de_4579c5_idx"
                    ),
                    models.Index(
                        fields=["code_str"], name="classifiers_code_st_8e9129_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_dec",
                    models.CharField(
                        default="",
                        max_length=4,
                        unique=True,
                        verbose_name="Код числовой",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Наименование"
                    ),
                ),
                (
                    "notation_national",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Условное обозначение (национальное)",
                    ),
                ),
                (
                    "notation_international",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Условное обозначение (международное)",
                    ),
                ),
                (
                    "code_national",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Код бквенный (национальный)",
                    ),
                ),
                (
                    "code_international",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Код бквенный (международный)",
                    ),
                ),
                (
                    "repr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерений",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["code_dec"], name="classifiers_code_de_75c019_idx"
                    ),
                    models.Index(
                        fields=["notation_national"],
                        name="classifiers_notatio_4563fe_idx",
                    ),
                ],
            },
        ),
    ]
